# Generated by Django 4.0.3 on 2022-04-11 14:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=32)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.stock')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user')),
            ],
        ),
    ]
